///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyEditProfileModelData = 'data';
const String _jsonKeyEditProfileModelDataUsername = 'username';
const String _jsonKeyEditProfileModelDataEmail = 'email';
const String _jsonKeyEditProfileModelDataFirstName = 'first_name';
const String _jsonKeyEditProfileModelDataLastName = 'last_name';
const String _jsonKeyEditProfileModelDataPhone = 'phone';
const String _jsonKeyEditProfileModelDataLicense = 'license';
class EditProfileModelData {
/*
{
  "username": "suhant",
  "email": "suhantkc@yahoo.com",
  "first_name": "Sushant",
  "last_name": "K.C",
  "phone": "9800203211",
  "license": null
}
*/

  String? username;
  String? email;
  String? firstName;
  String? lastName;
  String? phone;
  String? license;
  Map<String, dynamic> __origJson = {};

  EditProfileModelData({
    this.username,
    this.email,
    this.firstName,
    this.lastName,
    this.phone,
    this.license,
  });
  EditProfileModelData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    username = json[_jsonKeyEditProfileModelDataUsername]?.toString();
    email = json[_jsonKeyEditProfileModelDataEmail]?.toString();
    firstName = json[_jsonKeyEditProfileModelDataFirstName]?.toString();
    lastName = json[_jsonKeyEditProfileModelDataLastName]?.toString();
    phone = json[_jsonKeyEditProfileModelDataPhone]?.toString();
    license = json[_jsonKeyEditProfileModelDataLicense]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyEditProfileModelDataUsername] = username;
    data[_jsonKeyEditProfileModelDataEmail] = email;
    data[_jsonKeyEditProfileModelDataFirstName] = firstName;
    data[_jsonKeyEditProfileModelDataLastName] = lastName;
    data[_jsonKeyEditProfileModelDataPhone] = phone;
    data[_jsonKeyEditProfileModelDataLicense] = license;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class EditProfileModel {
/*
{
  "data": {
    "username": "suhant",
    "email": "suhantkc@yahoo.com",
    "first_name": "Sushant",
    "last_name": "K.C",
    "phone": "9800203211",
    "license": null
  }
}
*/

  EditProfileModelData? data;
  Map<String, dynamic> __origJson = {};

  EditProfileModel({
    this.data,
  });
  EditProfileModel.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    data = (json[_jsonKeyEditProfileModelData] != null && (json[_jsonKeyEditProfileModelData] is Map)) ? EditProfileModelData.fromJson(json[_jsonKeyEditProfileModelData]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data[_jsonKeyEditProfileModelData] = this.data!.toJson();
    }
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
