///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyPricingData = 'data';
const String _jsonKeyPricingDataId = 'id';
const String _jsonKeyPricingDataTypeOf = 'typeOf';
const String _jsonKeyPricingDataWeight = 'weight';
const String _jsonKeyPricingDataSize = 'size';
const String _jsonKeyPricingDataPrice = 'price';
class PricingData {
/*
{
  "id": 1,
  "typeOf": "Document",
  "weight": "Less than 1 kg",
  "size": "less than 1 m",
  "price": "500"
}
*/

  int? id;
  String? typeOf;
  String? weight;
  String? size;
  String? price;
  Map<String, dynamic> __origJson = {};

  PricingData({
    this.id,
    this.typeOf,
    this.weight,
    this.size,
    this.price,
  });
  PricingData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyPricingDataId]?.toString() ?? '');
    typeOf = json[_jsonKeyPricingDataTypeOf]?.toString();
    weight = json[_jsonKeyPricingDataWeight]?.toString();
    size = json[_jsonKeyPricingDataSize]?.toString();
    price = json[_jsonKeyPricingDataPrice]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyPricingDataId] = id;
    data[_jsonKeyPricingDataTypeOf] = typeOf;
    data[_jsonKeyPricingDataWeight] = weight;
    data[_jsonKeyPricingDataSize] = size;
    data[_jsonKeyPricingDataPrice] = price;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class Pricing {
/*
{
  "data": [
    {
      "id": 1,
      "typeOf": "Document",
      "weight": "Less than 1 kg",
      "size": "less than 1 m",
      "price": "500"
    }
  ]
}
*/

  List<PricingData?>? data;
  Map<String, dynamic> __origJson = {};

  Pricing({
    this.data,
  });
  Pricing.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json[_jsonKeyPricingData] != null && (json[_jsonKeyPricingData] is List)) {
      final v = json[_jsonKeyPricingData];
      final arr0 = <PricingData>[];
      v.forEach((v) {
        arr0.add(PricingData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyPricingData] = arr0;
    }
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
