///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyShipmentId = 'id';
const String _jsonKeyShipmentOfType = 'of_type';
const String _jsonKeyShipmentWeight = 'weight';
const String _jsonKeyShipmentSize = 'size';
const String _jsonKeyShipmentPrice = 'price';
const String _jsonKeyShipmentReceiver = 'receiver';
const String _jsonKeyShipmentPhoneNumber = 'phone_number';
const String _jsonKeyShipmentPackageType = 'package_type';
const String _jsonKeyShipmentStart = 'start';
const String _jsonKeyShipmentDestination = 'destination';
const String _jsonKeyShipmentStatus = 'status';
const String _jsonKeyShipmentEmail = 'email';
const String _jsonKeyShipmentDeliveryDate = 'delivery_date';
const String _jsonKeyShipmentPaymentType = 'payment_type';
const String _jsonKeyShipmentTrackingNumber = 'tracking_number';
class Shipment {
/*
{
  "id": 51,
  "of_type": "test001",
  "weight": "sdasda",
  "size": "12",
  "price": "sdafa",
  "receiver": "9808790371",
  "phone_number": "password",
  "package_type": "express",
  "start": "ja",
  "destination": "1231421",
  "status": "24145436",
  "email": "24145@gmail.com",
  "delivery_date": "April 1,2022",
  "payment_type": "khalti",
  "tracking_number": "476b8dd7-8ad4-4a47-98c7-44647ee9073e"
}
*/

  int? id;
  String? ofType;
  String? weight;
  String? size;
  String? price;
  String? receiver;
  String? phoneNumber;
  String? packageType;
  String? start;
  String? destination;
  String? status;
  String? email;
  String? deliveryDate;
  String? paymentType;
  String? trackingNumber;
  Map<String, dynamic> __origJson = {};

  Shipment({
    this.id,
    this.ofType,
    this.weight,
    this.size,
    this.price,
    this.receiver,
    this.phoneNumber,
    this.packageType,
    this.start,
    this.destination,
    this.status,
    this.email,
    this.deliveryDate,
    this.paymentType,
    this.trackingNumber,
  });
  Shipment.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyShipmentId]?.toString() ?? '');
    ofType = json[_jsonKeyShipmentOfType]?.toString();
    weight = json[_jsonKeyShipmentWeight]?.toString();
    size = json[_jsonKeyShipmentSize]?.toString();
    price = json[_jsonKeyShipmentPrice]?.toString();
    receiver = json[_jsonKeyShipmentReceiver]?.toString();
    phoneNumber = json[_jsonKeyShipmentPhoneNumber]?.toString();
    packageType = json[_jsonKeyShipmentPackageType]?.toString();
    start = json[_jsonKeyShipmentStart]?.toString();
    destination = json[_jsonKeyShipmentDestination]?.toString();
    status = json[_jsonKeyShipmentStatus]?.toString();
    email = json[_jsonKeyShipmentEmail]?.toString();
    deliveryDate = json[_jsonKeyShipmentDeliveryDate]?.toString();
    paymentType = json[_jsonKeyShipmentPaymentType]?.toString();
    trackingNumber = json[_jsonKeyShipmentTrackingNumber]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShipmentId] = id;
    data[_jsonKeyShipmentOfType] = ofType;
    data[_jsonKeyShipmentWeight] = weight;
    data[_jsonKeyShipmentSize] = size;
    data[_jsonKeyShipmentPrice] = price;
    data[_jsonKeyShipmentReceiver] = receiver;
    data[_jsonKeyShipmentPhoneNumber] = phoneNumber;
    data[_jsonKeyShipmentPackageType] = packageType;
    data[_jsonKeyShipmentStart] = start;
    data[_jsonKeyShipmentDestination] = destination;
    data[_jsonKeyShipmentStatus] = status;
    data[_jsonKeyShipmentEmail] = email;
    data[_jsonKeyShipmentDeliveryDate] = deliveryDate;
    data[_jsonKeyShipmentPaymentType] = paymentType;
    data[_jsonKeyShipmentTrackingNumber] = trackingNumber;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
