///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyShipmentUpdateData = 'data';
class ShipmentUpdate {
/*
{
  "data": "On Route"
}
*/

  String? data;
  Map<String, dynamic> __origJson = {};

  ShipmentUpdate({
    this.data,
  });
  ShipmentUpdate.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    data = json[_jsonKeyShipmentUpdateData]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShipmentUpdateData] = this.data;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
