///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyShipmentListData = 'data';
const String _jsonKeyShipmentListDataId = 'id';
const String _jsonKeyShipmentListDataOfType = 'of_type';
const String _jsonKeyShipmentListDataWeight = 'weight';
const String _jsonKeyShipmentListDataSize = 'size';
const String _jsonKeyShipmentListDataPrice = 'price';
const String _jsonKeyShipmentListDataReceiver = 'receiver';
const String _jsonKeyShipmentListDataPhoneNumber = 'phone_number';
const String _jsonKeyShipmentListDataPackageType = 'package_type';
const String _jsonKeyShipmentListDataStart = 'start';
const String _jsonKeyShipmentListDataDestination = 'destination';
const String _jsonKeyShipmentListDataStatus = 'status';
const String _jsonKeyShipmentListDataEmail = 'email';
const String _jsonKeyShipmentListDataDeliveryDate = 'delivery_date';
const String _jsonKeyShipmentListDataPaymentType = 'payment_type';
const String _jsonKeyShipmentListDataTrackingNumber = 'tracking_number';
class ShipmentListData {
/*
{
  "id": 68,
  "of_type": "parcel",
  "weight": "1",
  "size": "1.188",
  "price": "840.0",
  "receiver": "Suman Shrestha",
  "phone_number": "9801323121",
  "package_type": "Standard",
  "start": "Labim Mall",
  "destination": "Civil Mall",
  "status": "Processing",
  "email": "suman@gmail.com",
  "delivery_date": "April 6, 2022",
  "payment_type": "Cash On Delivery",
  "tracking_number": "84a860f5-a150-496a-ae7d-ceaa8eff45d0"
}
*/

  int? id;
  String? ofType;
  String? weight;
  String? size;
  String? price;
  String? receiver;
  String? phoneNumber;
  String? packageType;
  String? start;
  String? destination;
  String? status;
  String? email;
  String? deliveryDate;
  String? paymentType;
  String? trackingNumber;
  Map<String, dynamic> __origJson = {};

  ShipmentListData({
    this.id,
    this.ofType,
    this.weight,
    this.size,
    this.price,
    this.receiver,
    this.phoneNumber,
    this.packageType,
    this.start,
    this.destination,
    this.status,
    this.email,
    this.deliveryDate,
    this.paymentType,
    this.trackingNumber,
  });
  ShipmentListData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyShipmentListDataId]?.toString() ?? '');
    ofType = json[_jsonKeyShipmentListDataOfType]?.toString();
    weight = json[_jsonKeyShipmentListDataWeight]?.toString();
    size = json[_jsonKeyShipmentListDataSize]?.toString();
    price = json[_jsonKeyShipmentListDataPrice]?.toString();
    receiver = json[_jsonKeyShipmentListDataReceiver]?.toString();
    phoneNumber = json[_jsonKeyShipmentListDataPhoneNumber]?.toString();
    packageType = json[_jsonKeyShipmentListDataPackageType]?.toString();
    start = json[_jsonKeyShipmentListDataStart]?.toString();
    destination = json[_jsonKeyShipmentListDataDestination]?.toString();
    status = json[_jsonKeyShipmentListDataStatus]?.toString();
    email = json[_jsonKeyShipmentListDataEmail]?.toString();
    deliveryDate = json[_jsonKeyShipmentListDataDeliveryDate]?.toString();
    paymentType = json[_jsonKeyShipmentListDataPaymentType]?.toString();
    trackingNumber = json[_jsonKeyShipmentListDataTrackingNumber]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShipmentListDataId] = id;
    data[_jsonKeyShipmentListDataOfType] = ofType;
    data[_jsonKeyShipmentListDataWeight] = weight;
    data[_jsonKeyShipmentListDataSize] = size;
    data[_jsonKeyShipmentListDataPrice] = price;
    data[_jsonKeyShipmentListDataReceiver] = receiver;
    data[_jsonKeyShipmentListDataPhoneNumber] = phoneNumber;
    data[_jsonKeyShipmentListDataPackageType] = packageType;
    data[_jsonKeyShipmentListDataStart] = start;
    data[_jsonKeyShipmentListDataDestination] = destination;
    data[_jsonKeyShipmentListDataStatus] = status;
    data[_jsonKeyShipmentListDataEmail] = email;
    data[_jsonKeyShipmentListDataDeliveryDate] = deliveryDate;
    data[_jsonKeyShipmentListDataPaymentType] = paymentType;
    data[_jsonKeyShipmentListDataTrackingNumber] = trackingNumber;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class ShipmentList {
/*
{
  "data": [
    {
      "id": 68,
      "of_type": "parcel",
      "weight": "1",
      "size": "1.188",
      "price": "840.0",
      "receiver": "Suman Shrestha",
      "phone_number": "9801323121",
      "package_type": "Standard",
      "start": "Labim Mall",
      "destination": "Civil Mall",
      "status": "Processing",
      "email": "suman@gmail.com",
      "delivery_date": "April 6, 2022",
      "payment_type": "Cash On Delivery",
      "tracking_number": "84a860f5-a150-496a-ae7d-ceaa8eff45d0"
    }
  ]
}
*/

  List<ShipmentListData?>? data;
  Map<String, dynamic> __origJson = {};

  ShipmentList({
    this.data,
  });
  ShipmentList.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json[_jsonKeyShipmentListData] != null && (json[_jsonKeyShipmentListData] is List)) {
      final v = json[_jsonKeyShipmentListData];
      final arr0 = <ShipmentListData>[];
      v.forEach((v) {
        arr0.add(ShipmentListData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyShipmentListData] = arr0;
    }
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
