///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyShipmentFinishData = 'data';
class ShipmentFinish {
/*
{
  "data": "Delivered"
}
*/

  String? data;
  Map<String, dynamic> __origJson = {};

  ShipmentFinish({
    this.data,
  });
  ShipmentFinish.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    data = json[_jsonKeyShipmentFinishData]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyShipmentFinishData] = this.data;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
